server:
  port: 6569

spring:
  application:
    name: shipments-api-java8

# -------------------------------------------------------------------
# Logging settings
# -------------------------------------------------------------------
logging:
  level:
    io:
      github:
        bhuwanupadhyay: DEBUG
# -------------------------------------------------------------------
# Shipments configurations
# -------------------------------------------------------------------
shipments:
  orders-api:
    base-url: ${SHIPMENTS_API_BASE_URL:http://localhost:6569}
